#!/usr/bin/env bash

# clone the repo
git clone --bare https://github.com/mknap/dotfiles.git $HOME/dotfiles

# define config alias locally since the dotfiles
# aren't installed on the system yet
function config {
   git --git-dir=$HOME/dotfiles/ --work-tree=$HOME $@
}

# create a directory to backup existing dotfiles to
mkdir -p $HOME/.dotfiles-backup
config checkout
if [ $? = 0 ]; then
  echo "Checking out dotfiles from git@github.com:mknap/dotfiles.git";
  else
    echo "Moving existing dotfiles to ~/.dotfiles-backup";
      # This mv command doesn't work with tree structures like .config/hypr/config/file.conf:
      #config checkout 2>&1 | grep -E "\s+\." | awk {'print $1'} | xargs -I{} mv {} $HOME/.dotfiles-backup/{}
   config checkout 2>&1 | grep -E "\s+\." | awk {'print $1'} | xargs -I{} sh -c 'cp {} $HOME/.dotfiles-backup/ && rm {}'
fi

# checkout dotfiles from repo
config checkout
config config status.showUntrackedFiles no
